apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app:demo
    spec:
      containers:
      - name: demo
        image: 172.18.118.234/fcloud-appimage/demo:0.0.1-SNAPSHOT
        imagePullPolicy: Always
        
